# options applied to prune images
image:
  # active defines where images will be pruned or not
  active: false

  # prune all images 
  all: false

  # only remove containers created before given timestamp 
  # until can be a unix timestamp, a go duration or a date
  # see https://docs.docker.com/engine/reference/commandline/image_prune/ for more information
  until: 10m
  
  # exclude all images with the following labels
  # labels can be provided as key-value pairs separted with a "="
  excludeLabels:
    - bermuda.exclude

  # include all images with the following labels
  # labels can be provided as key-value pairs separted with a "="
  includeLabels:
    - bermuda.include

# options applied to prune containers
container:
  active: false
  until: 10m
  excludeLabels:
    - bermuda.exclude
  includeLabels:
    - bermuda.include

logging:
  logfile: ./bermuda.log
  verbose: false